// AUTO-GENERATED by scripts/generate-road-ahead-manifest.mjs — do not edit by hand.
// Regenerated on every build (prebuild hook) from public/road-ahead/**. Lists the
// media present at build so the resolver never touches the filesystem at request
// time (serverless/ISR-safe). Empty = no owner media supplied yet.
export const PRESENT_ASSETS: readonly string[] = [];

// slot id → YouTube-Unlisted video id (from public/road-ahead/youtube-sources.json).
export const YOUTUBE_SOURCES: Readonly<Record<string, string>> = {
  "dark-highway": "OfM4krgRqcw",
  "late-night-driving": "PQPWyX98fMU",
  "night-driving": "wsanOA1aJ1U",
  "pretrip": "Okpkg_xjwX8",
  "sunrise": "8E6U04-K3qA",
  "truck-driving-away": "0xgnGSxdMGI",
  "truck-walkaround": "UgB8CPtzjSg"
};

// slot id → resolved cinematic MOMENT (segment + edits) from
// public/road-ahead/footage.json. Takes precedence over YOUTUBE_SOURCES for the
// same slot. `file` is validated against PRESENT_ASSETS by the resolver.
export type GeneratedMoment = {
  youtubeId: string | null;
  file: string | null;
  poster: string | null;
  start: number | null;
  end: number | null;
  speed: number | null;
  loop: boolean;
  crop: string | null;
  zoom: number | null;
  grade: string;
  fadeIn: number | null;
  fadeOut: number | null;
  duck: boolean;
  mobile: Record<string, unknown> | null;
};
export const FOOTAGE_MOMENTS: Readonly<Record<string, GeneratedMoment>> = {};
