// AUTO-GENERATED by scripts/generate-road-ahead-manifest.mjs — do not edit by hand.
// Regenerated on every build (prebuild hook) from public/road-ahead/**. Lists the
// media present at build so the resolver never touches the filesystem at request
// time (serverless/ISR-safe). Empty = no owner media supplied yet.
export const PRESENT_ASSETS: readonly string[] = [];

// slot id → YouTube-Unlisted video id (from public/road-ahead/youtube-sources.json).
export const YOUTUBE_SOURCES: Readonly<Record<string, string>> = {
  "night-driving": "wsanOA1aJ1U"
};
