import type { MetadataRoute } from 'next';
import { SITE } from '@/lib/seo/site';
import { createStaticClient } from '@/lib/supabase/static';
import { DIRECTORY_CATEGORIES, categoryHref } from '@/lib/directory/categories';
import {
  getDirectoryFacets,
  getAllPublishedEntries,
  getParkingFacets,
  getCatScaleFacets,
} from '@/lib/directory/data';
import { stateByCode } from '@/lib/directory/states';
import { interstateSlug, exitSlug } from '@/lib/directory/interstates';
import { interstateToSlug, directionsForInterstate } from '@/lib/directory/corridor';
import { isDetailIndexable } from '@/lib/directory/detail';
import { detailHref } from '@/lib/directory/detail-slug';
import { STORE_CATEGORIES, storeCategoryHref } from '@/lib/store/categories';
import {
  STORE_PRODUCTS,
  productHref,
  productsInCategory,
  productsOfType,
} from '@/lib/store/products';
import { shawnsPicks } from '@/lib/store/picks';
import { DIRECT_PRODUCTS, directProductHref, SHIPPING_RETURNS_HREF } from '@/lib/store/direct';
import { STORE_GUIDES, guideHref } from '@/lib/store/product-types';
import { publishedTests, testHref } from '@/lib/tests/catalog';

/**
 * Sitemap URL generation, segmented by family (SEO blueprint PR-D,
 * owner decision #6, 2026-08-17).
 *
 * /sitemap.xml stays the STABLE ENTRY POINT — it is now a sitemap index
 * whose five children partition the same URL set the single sitemap carried,
 * so Search Console can report Discovered/Indexed per family:
 *
 *   core                 — statics, academy, CDL Pre-School, Knowledge
 *                          Center, store, practice tests
 *   directory-hubs       — directory statics + categories, state pages,
 *                          corridors, and the flow state/corridor steps
 *   directory-exits      — /directory/i-NN/exit-NN pages (the 30-day
 *                          measurement control cohort)
 *   directory-directions — the flow direction pages (kept-vs-canonicalize
 *                          is decided at the 30-day gate on this family's
 *                          own GSC numbers)
 *   directory-details    — per-listing detail pages past the indexability
 *                          gate
 *
 * Every family is generated by the same registries, facet reads, and shared
 * gate as before; the partition (pairwise disjoint, union = the whole) is
 * enforced by scripts/test-sitemap-contract.ts.
 *
 * lastModified policy (PR-A, unchanged): a <lastmod> is emitted ONLY where a
 * real, persisted content-modification date exists — listing detail pages
 * (locations.updated_at) and Knowledge Center articles
 * (kc_articles.updated_at). Every other entry omits the field. Never
 * substitute build/request/deploy time for a modification date.
 */

export const SITEMAP_FAMILIES = [
  'core',
  'directory-hubs',
  'directory-exits',
  'directory-directions',
  'directory-details',
] as const;

export type SitemapFamily = (typeof SITEMAP_FAMILIES)[number];

/** Path of a child sitemap, relative to the site origin. */
export function familySitemapPath(family: SitemapFamily): string {
  return `/sitemaps/${family}.xml`;
}

/* ------------------------------------------------------------------ core */

/**
 * Statics, academy, CDL Pre-School, store, practice tests, and the
 * Knowledge Center (categories + published articles, with real updated_at).
 */
export async function coreEntries(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [
    { url: SITE.url, changeFrequency: 'weekly', priority: 1 },
    { url: `${SITE.url}/knowledge`, changeFrequency: 'daily', priority: 0.9 },
    // Founders Wall (Milestone 9).
    { url: `${SITE.url}/founders`, changeFrequency: 'weekly', priority: 0.8 },
    // CDL Pre-School (Founding Student offer).
    {
      url: `${SITE.url}/cdl-pre-school`,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${SITE.url}/cdl-pre-school/founding-students`,
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${SITE.url}/cdl-pre-school/founding-student-claim`,
      changeFrequency: 'monthly',
      priority: 0.4,
    },
  ];

  // Top-level public destinations. `/directory/parking` deliberately is NOT
  // here: it is the `parking` category's `customHref`, so the
  // directory-hubs family emits it. Listing it twice would put a duplicate
  // <url> across children and break the partition.
  const topLevelPaths: Array<[string, number]> = [
    ['/road-ahead', 0.7],
    ['/trip-planner', 0.8],
    ['/books', 0.8],
    ['/apps', 0.6],
    ['/sponsors', 0.6],
    ['/dot-tools', 0.6],
    ['/tools/hos-calculator', 0.7],
    ['/supply-the-classroom', 0.8],
    ['/privacy', 0.3],
    ['/terms', 0.3],
    ['/sms-terms', 0.3],
  ];
  for (const [path, priority] of topLevelPaths) {
    entries.push({
      url: `${SITE.url}${path}`,
      changeFrequency: 'weekly',
      priority,
    });
  }

  // Academy module (Milestone 7) — static routes.
  const academyPaths = [
    '/academy',
    '/academy/curriculum',
    '/academy/requirements',
    '/academy/financing',
    '/academy/facility',
    '/academy/instructors',
    '/academy/faq',
    '/academy/cdl-school-dalton-ga',
    '/academy/apply',
  ];
  for (const path of academyPaths) {
    entries.push({
      url: `${SITE.url}${path}`,
      changeFrequency: 'weekly',
      priority: path === '/academy' ? 0.9 : 0.7,
    });
  }

  // Trucking Life Store — hub, every category, and every product. Placeholder
  // products are still crawlable content pages (no active affiliate link until
  // an ASIN is confirmed), so they belong in the sitemap.
  entries.push({
    url: `${SITE.url}/store`,
    changeFrequency: 'weekly',
    priority: 0.8,
  });
  // Physical-product policy — public and stable.
  entries.push({
    url: `${SITE.url}${SHIPPING_RETURNS_HREF}`,
    changeFrequency: 'yearly',
    priority: 0.4,
  });
  // Trucking Life's own products — always public, so always listed.
  for (const product of DIRECT_PRODUCTS) {
    entries.push({
      url: `${SITE.url}${directProductHref(product.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }
  // Only categories that actually have a publicly visible product. A category
  // whose products are all hidden renders an empty page — submitting it would
  // be asking Google to index nothing.
  for (const category of STORE_CATEGORIES) {
    if (productsInCategory(category.slug).length === 0) continue;
    entries.push({
      url: `${SITE.url}${storeCategoryHref(category.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }
  for (const product of STORE_PRODUCTS) {
    entries.push({
      url: `${SITE.url}${productHref(product.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.6,
    });
  }
  // Buying guides (M54) + Shawn's Picks — each listed only while it still has
  // visible products to show, for the same reason as the categories above.
  const visibleGuides = STORE_GUIDES.filter((g) => productsOfType(g.productType).length > 0);
  if (visibleGuides.length > 0) {
    entries.push({
      url: `${SITE.url}/store/guides`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }
  if (shawnsPicks().length > 0) {
    entries.push({
      url: `${SITE.url}/store/shawns-picks`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }
  for (const guide of visibleGuides) {
    entries.push({
      url: `${SITE.url}${guideHref(guide.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }

  // Practice Tests (Milestone 1) — hub + every published test landing. Tests
  // render from the TS catalog, so their URLs ship even before a bank is seeded.
  entries.push({
    url: `${SITE.url}/practice-tests`,
    changeFrequency: 'weekly',
    priority: 0.8,
  });
  for (const test of publishedTests()) {
    entries.push({
      url: `${SITE.url}${testHref(test.slug)}`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }

  // Knowledge Center categories + published articles.
  try {
    const supabase = createStaticClient();
    const { data: cats } = await supabase
      .from('kc_categories')
      .select('slug')
      .eq('is_active', true);
    for (const c of cats ?? []) {
      entries.push({
        url: `${SITE.url}/knowledge/${(c as { slug: string }).slug}`,
        changeFrequency: 'weekly',
        priority: 0.7,
      });
    }
    const { data: arts } = await supabase
      .from('kc_articles')
      .select('slug, updated_at, kc_categories!inner(slug)')
      .eq('status', 'published');
    for (const a of arts ?? []) {
      const row = a as unknown as {
        slug: string;
        updated_at: string | null;
        kc_categories: { slug: string };
      };
      // Same policy as detail pages: only the article's own updated_at, and
      // only when the row actually carries one.
      entries.push({
        url: `${SITE.url}/knowledge/${row.kc_categories.slug}/${row.slug}`,
        ...(row.updated_at ? { lastModified: new Date(row.updated_at) } : {}),
        changeFrequency: 'monthly',
        priority: 0.6,
      });
    }
  } catch {
    // If the DB is unreachable at build, still ship the static entries.
  }

  return dedupeByUrl(entries);
}

/* -------------------------------------------------------- directory-hubs */

/**
 * Directory statics + categories + state pages + corridors + the parking /
 * CAT-scale flow state and corridor steps. Direction pages are their own
 * family (below) so their indexing can be measured separately.
 */
export async function directoryHubEntries(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [];

  // Directory Engine (Milestone 11) — hub + every category in the registry.
  entries.push({
    url: `${SITE.url}/directory`,
    changeFrequency: 'weekly',
    priority: 0.8,
  });
  // Public interactive map (Milestone 19).
  entries.push({
    url: `${SITE.url}/directory/map`,
    changeFrequency: 'weekly',
    priority: 0.8,
  });
  // Driver community (Milestone 16): submissions + reviews.
  entries.push(
    {
      url: `${SITE.url}/directory/submit`,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${SITE.url}/directory/reviews`,
      changeFrequency: 'daily',
      priority: 0.7,
    },
    // Growth surfaces (Milestone 25).
    {
      url: `${SITE.url}/directory/recently-updated`,
      changeFrequency: 'daily',
      priority: 0.6,
    },
    {
      url: `${SITE.url}/directory/new-locations`,
      changeFrequency: 'daily',
      priority: 0.6,
    },
  );
  for (const category of DIRECTORY_CATEGORIES) {
    entries.push({
      url: `${SITE.url}${categoryHref(category)}`,
      changeFrequency: 'weekly',
      priority: 0.7,
    });
  }

  // State pages and interstate corridors come from the published data itself.
  try {
    const facets = await getDirectoryFacets();
    for (const code of facets.states) {
      const state = stateByCode(code);
      if (!state) continue;
      entries.push({
        url: `${SITE.url}/directory/${state.slug}`,
        changeFrequency: 'weekly',
        priority: 0.7,
      });
      // Top-truck-stops landing page for the state (Milestone 25).
      entries.push({
        url: `${SITE.url}/directory/${state.slug}/top-truck-stops`,
        changeFrequency: 'weekly',
        priority: 0.6,
      });
    }
    for (const designation of facets.interstates) {
      const slug = interstateSlug(designation);
      if (!slug) continue;
      entries.push({
        url: `${SITE.url}/directory/${slug}`,
        changeFrequency: 'weekly',
        priority: 0.7,
      });
      // Corridor parking landing page (Milestone 25).
      entries.push({
        url: `${SITE.url}/directory/${slug}/truck-parking`,
        changeFrequency: 'weekly',
        priority: 0.6,
      });
    }
  } catch {
    // Facet URLs are additive — a DB hiccup still ships the rest.
  }

  // Corridor-flow state + corridor steps and the CAT Scale Near Me search.
  entries.push({
    url: `${SITE.url}/directory/cat-scales/near-me`,
    changeFrequency: 'weekly',
    priority: 0.7,
  });
  try {
    for (const { base, facets } of await flowFacets()) {
      for (const { code } of facets.states) {
        if (!stateByCode(code)) continue;
        const statePath = `${base}/${code.toLowerCase()}`;
        entries.push({
          url: `${SITE.url}${statePath}`,
          changeFrequency: 'weekly',
          priority: 0.6,
        });
        for (const { designation } of facets.interstatesByState[code] ?? []) {
          entries.push({
            url: `${SITE.url}${statePath}/${interstateToSlug(designation)}`,
            changeFrequency: 'weekly',
            priority: 0.6,
          });
        }
      }
    }
  } catch {
    // Corridor-flow URLs are additive too.
  }

  return dedupeByUrl(entries);
}

/* ------------------------------------------------------- directory-exits */

/** Exit pages, from the same canonicalized facets the pages resolve with. */
export async function directoryExitEntries(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [];
  try {
    const facets = await getDirectoryFacets();
    for (const designation of facets.interstates) {
      const slug = interstateSlug(designation);
      if (!slug) continue;
      for (const exit of facets.exitsByInterstate[designation] ?? []) {
        entries.push({
          url: `${SITE.url}/directory/${slug}/${exitSlug(exit)}`,
          changeFrequency: 'weekly',
          priority: 0.6,
        });
      }
    }
  } catch {
    // Additive.
  }
  return dedupeByUrl(entries);
}

/* -------------------------------------------------- directory-directions */

/**
 * The flow direction pages — route-ordered re-sorts of their corridor
 * steps. Their own child sitemap so the day-30 keep-vs-canonicalize
 * decision (settled decision #4) reads real per-family GSC numbers.
 */
export async function directoryDirectionEntries(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [];
  try {
    for (const { base, facets } of await flowFacets()) {
      for (const { code } of facets.states) {
        if (!stateByCode(code)) continue;
        const statePath = `${base}/${code.toLowerCase()}`;
        for (const { designation } of facets.interstatesByState[code] ?? []) {
          const corridorPath = `${statePath}/${interstateToSlug(designation)}`;
          for (const direction of directionsForInterstate(designation)) {
            entries.push({
              url: `${SITE.url}${corridorPath}/${direction}`,
              changeFrequency: 'weekly',
              priority: 0.6,
            });
          }
        }
      }
    }
  } catch {
    // Additive.
  }
  return dedupeByUrl(entries);
}

/* ----------------------------------------------------- directory-details */

/**
 * Per-listing detail pages (Milestone 20). Only pages past the shared
 * indexability gate are listed — thin listings render with noindex,follow
 * and stay out of the sitemap until their data fills in.
 */
export async function directoryDetailEntries(): Promise<MetadataRoute.Sitemap> {
  const entries: MetadataRoute.Sitemap = [];
  try {
    const listings = await getAllPublishedEntries();
    for (const entry of listings) {
      if (!entry.detailSlug || !isDetailIndexable(entry)) continue;
      // Real modification date only; a row without one gets no <lastmod>
      // rather than a fabricated "now".
      entries.push({
        url: `${SITE.url}${detailHref(entry.detailSlug)}`,
        ...(entry.updatedAt ? { lastModified: new Date(entry.updatedAt) } : {}),
        changeFrequency: 'weekly',
        priority: 0.6,
      });
    }
  } catch {
    // Additive.
  }
  return dedupeByUrl(entries);
}

/* ----------------------------------------------------------- composition */

const FAMILY_FNS: Record<SitemapFamily, () => Promise<MetadataRoute.Sitemap>> = {
  core: coreEntries,
  'directory-hubs': directoryHubEntries,
  'directory-exits': directoryExitEntries,
  'directory-directions': directoryDirectionEntries,
  'directory-details': directoryDetailEntries,
};

export function entriesForFamily(family: SitemapFamily): Promise<MetadataRoute.Sitemap> {
  return FAMILY_FNS[family]();
}

/**
 * The union of every family, in family order, deduped — byte-equivalent to
 * what the single pre-PR-D sitemap carried. Harnesses assert the contract
 * against this; the partition test asserts the children never overlap, so
 * the dedupe here is a belt-and-suspenders guard, not a load-bearing merge.
 */
export async function allSitemapEntries(): Promise<MetadataRoute.Sitemap> {
  const all: MetadataRoute.Sitemap = [];
  for (const family of SITEMAP_FAMILIES) {
    all.push(...(await entriesForFamily(family)));
  }
  return dedupeByUrl(all);
}

/** Both flow trees with their facets — shared by hubs and directions. */
async function flowFacets() {
  return [
    { base: '/directory/parking', facets: await getParkingFacets() },
    { base: '/directory/cat-scales', facets: await getCatScaleFacets() },
  ];
}

function dedupeByUrl(entries: MetadataRoute.Sitemap): MetadataRoute.Sitemap {
  const seen = new Set<string>();
  const out: MetadataRoute.Sitemap = [];
  for (const entry of entries) {
    if (seen.has(entry.url)) continue;
    seen.add(entry.url);
    out.push(entry);
  }
  return out;
}

/* -------------------------------------------------------- XML rendering */

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** <urlset> document for one child sitemap. */
export function urlsetXml(entries: MetadataRoute.Sitemap): string {
  const urls = entries
    .map((e) => {
      const lastmod = e.lastModified
        ? `<lastmod>${new Date(e.lastModified as string | Date).toISOString()}</lastmod>`
        : '';
      const changefreq = e.changeFrequency ? `<changefreq>${e.changeFrequency}</changefreq>` : '';
      const priority = e.priority != null ? `<priority>${e.priority}</priority>` : '';
      return `<url><loc>${xmlEscape(e.url)}</loc>${lastmod}${changefreq}${priority}</url>`;
    })
    .join('');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls}</urlset>`
  );
}

/**
 * The <sitemapindex> served at /sitemap.xml — the stable entry point.
 * No <lastmod> on children: same honesty rule as the URLs themselves.
 */
export function sitemapIndexXml(): string {
  const children = SITEMAP_FAMILIES.map(
    (f) => `<sitemap><loc>${xmlEscape(`${SITE.url}${familySitemapPath(f)}`)}</loc></sitemap>`,
  ).join('');
  return (
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${children}</sitemapindex>`
  );
}
